server:
    port: 10344
    address: localhost

spring:
    profiles:
        active: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: devProductsDB   
             